Dicision tree

 >classification algorithm...
 its follows tree like structure to ptredict the o/p


  <img src=https://miro.medium.com/v2/resize:fit:1430/1*rSQIIAboJftqAv_BReNipg.png>

In [64]:
import pandas as pd
import numpy as np

In [65]:
df = pd.read_excel("/content/tennis_anyone_1000 (1).xlsx")

In [66]:
df.head()

  Day ID   Outlook Temperature Humidity    Wind Play Tennis
0  Day_1  Overcast        Cool   Normal  Strong         Yes
1  Day_2      Rain        Mild     High    Weak         Yes
2  Day_3  Overcast         Hot   Normal    Weak         Yes
3  Day_4     Sunny        Mild   Normal  Strong         Yes
4  Day_5     Sunny        Mild     High    Weak          No

In [67]:
df.nunique()

Day ID         1000
Outlook           3
Temperature       3
Humidity          2
Wind              2
Play Tennis       2
dtype: int64

In [68]:
df.columns

Index(['Day ID', 'Outlook', 'Temperature', 'Humidity', 'Wind', 'Play Tennis'], dtype='object')

In [69]:
df.drop(columns='Day ID',inplace=True)

In [70]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Outlook']=le.fit_transform(df['Outlook']) #overcost-0,rain-1,sunny
df['Temperature']=le.fit_transform(df['Temperature']) #Cool-0,Mild-1,Hot-2
df['Humidity']=le.fit_transform(df['Humidity'])#Normal-0,high=1
df['Wind']=le.fit_transform(df['Wind'])#Strong - week-1
df['Play Tennis']=le.fit_transform(df['Play Tennis'])#yes=1,no-0

In [71]:
df.head()

   Outlook  Temperature  Humidity  Wind  Play Tennis
0        0            0         1     0            1
1        1            2         0     1            1
2        0            1         1     1            1
3        2            2         1     0            1
4        2            2         0     1            0

In [72]:
### renaming the columns
df.rename(columns={'play Tennis':'playTennis'},inplace=True)

In [73]:
df.head()

   Outlook  Temperature  Humidity  Wind  Play Tennis
0        0            0         1     0            1
1        1            2         0     1            1
2        0            1         1     1            1
3        2            2         1     0            1
4        2            2         0     1            0

In [74]:
df['Play Tennis'].value_counts()

Play Tennis
1    651
0    349
Name: count, dtype: int64

In [75]:
df.shape

(1000, 5)

In [76]:
#### splitting dataset vertcially(input/output)
x = df.iloc[:,0:-1]
y = df.iloc[:,-1]

In [77]:
x

     Outlook  Temperature  Humidity  Wind
0          0            0         1     0
1          1            2         0     1
2          0            1         1     1
3          2            2         1     0
4          2            2         0     1
..       ...          ...       ...   ...
995        2            2         0     1
996        0            2         0     0
997        1            2         0     0
998        0            0         1     0
999        1            2         1     1

[1000 rows x 4 columns]

In [78]:
y

0      1
1      1
2      1
3      1
4      0
      ..
995    0
996    1
997    0
998    1
999    1
Name: Play Tennis, Length: 1000, dtype: int64

In [79]:
## splitting dataset horizontally(train and test set(20%))
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [80]:
#### using decision Tree model
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()
dt

DecisionTreeClassifier()

In [81]:
# training the model
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [82]:
#### predict

predict = dt.predict(x_test)

In [84]:
### evaluating model
from sklearn.metrics import classification_report


print(classification_report(y_test,predict))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        69
           1       1.00      1.00      1.00       131

    accuracy                           1.00       200
   macro avg       1.00      1.00      1.00       200
weighted avg       1.00      1.00      1.00       200

Dicision Tree accurancy with 100 %